version: '3.9'

services:
  glassforge:
    container_name: glassforge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["bash"]
    stdin_open: true
    tty: true
    env_file:
      - .env